"""Fix foreign key reference

Revision ID: f1a42e464729
Revises: ad391e4553f7
Create Date: 2025-02-02 08:41:11.546364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1a42e464729'
down_revision = 'ad391e4553f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_code_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('forum_membership_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'class_code', ['class_code_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['student_id'], ['id'])
        batch_op.drop_column('class_code')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_membership', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('class_code', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('forum_membership_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_column('joined_at')
        batch_op.drop_column('student_id')
        batch_op.drop_column('class_code_id')

    # ### end Alembic commands ###
